runtime: python310
entrypoint: gunicorn -b :$PORT app:app

instance_class: F1  # Lower cost instance, adjust as needed

automatic_scaling:
  target_cpu_utilization: 0.85
  target_throughput_utilization: 0.85
  max_instances: 3  # Increased to handle more traffic if needed
  min_instances: 1
  max_idle_instances: 0
  min_idle_instances: 0

handlers:
- url: /static
  static_dir: static
  http_headers:
    Cache-Control: "public, max-age=86400"  # Cache static files for 1 day

- url: /.*
  secure: always
  script: auto

env_variables:
  GAE_ENV: 'standard'
  MAX_CONTENT_LENGTH: 3145728  # 3 MB
  SEND_FILE_MAX_AGE_DEFAULT: 86400  # Cache static files for 1 day

health_check:
  enable_health_check: true
  check_interval_sec: 120
  timeout_sec: 4
  unhealthy_threshold: 3
  healthy_threshold: 2

readiness_check:
  check_interval_sec: 30
  timeout_sec: 300

beta_settings:
  cloud_sql_instances: "les-socialites-chat-gpt:us-east1:wyzard"
  min_idle_instances: 0
  max_idle_instances: 0
