runtime: python310
entrypoint: gunicorn -b :$PORT app:app

instance_class: F4  # Lower cost instance

automatic_scaling:
  target_cpu_utilization: 0.75
  target_throughput_utilization: 0.85
  max_instances: 5
  min_instances: 1
  max_idle_instances: 1
  min_idle_instances: 0

# basic_scaling:
#   max_instances: 5  # Adjust based on expected traffic
#   idle_timeout: 10m  # Instances shut down after being idle for 10 minutes


handlers:
- url: /.*
  script: auto

env_variables:
  GAE_ENV: 'standard'

health_check:
  enable_health_check: true
  check_interval_sec: 60
  timeout_sec: 4
  unhealthy_threshold: 3
  healthy_threshold: 2

readiness_check:
  check_interval_sec: 10
  timeout_sec: 300
