runtime: python310
entrypoint: gunicorn -b :$PORT app:app

instance_class: F4_1G  # A higher class with more CPU and memory

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_instances: 10  # Adjust this based on expected traffic
  min_instances: 2    # Keep a minimum of 2 instances running
  max_idle_instances: 3  # Limits the number of idle instances to prevent unnecessary costs
  min_idle_instances: 1  # Keeps at least one idle instance ready

handlers:
- url: /.*
  script: auto

inbound_services:
- warmup  # Enable warmup requests to reduce latency spikes during scaling

env_variables:
  GAE_ENV: 'standard'  # Ensures the environment variable is set for the standard environment

# Optional: If your app uses health checks
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

readiness_check:
  check_interval_sec: 5
  timeout_sec: 300
